version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  backend:
    container_name: backend
    build: ./
    ports:
      - "8081:8080"
    depends_on:
      - postgres