server:
  port: 8080


spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/demo?createDatabaseIfNotExist=true
    username: root
    password: root
  #    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false


